language: rust

env: # required for matrix.allow_failures

matrix:
  fast_finish: true

  include:
      - if: NOT type = pull_request
        rust: nightly
        env: UNSTABLE=1 COVERAGE=1
        sudo: required

      - if: NOT type = pull_request
        rust: nightly
        services: docker
        env: TARGET=i686-unknown-linux-gnu UNSTABLE=1
        sudo: required
        addons:
          apt:
            packages:
              - gcc-multilib

      - if: NOT type = pull_request
        rust: beta

      - if: NOT type = pull_request
        rust: 1.20.0

      - if: NOT type = pull_request
        rust: stable
        services: docker
        env: TARGET=mips64-unknown-linux-gnuabi64
        sudo: required

      - rust: stable
        env: COVERAGE=1
        sudo: required

  allow_failures:
      - rust: stable
        services: docker
        env: TARGET=mips64-unknown-linux-gnuabi64
        sudo: required

cache: cargo
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - ./ci/script.sh

branches:
  only:
    - staging
    - trying
    - master
