[package]

name = "slow_primes"
version = "0.1.10"
authors = ["Huon Wilson <dbau.pp@gmail.com>"]

homepage = "https://github.com/huonw/slow_primes"
repository = "https://github.com/huonw/slow_primes"
documentation = "http://huonw.github.io/slow_primes/slow_primes/"
license = "MIT/Apache-2.0"
keywords = ["math", "mathematics", "primes", "number-theory"]
readme = "README.md"
description = """
A library to generate, identify and handle prime numbers and related
properties.  This library includes slow enumeration of primes up to a
bound, slow factorisation of arbitrary numbers, fast primality tests
and state-of-the-art estimation of upper and lower bounds for Ï€(n)
(the number of primes below n) and p_k (the k-th prime).
"""

[dependencies]
num = "~0"
