[package]
name = "primal-slowsieve"
version = "0.2.0"
authors = ["Huon Wilson <dbau.pp@gmail.com>"]

homepage = "https://github.com/huonw/primal"
repository = "https://github.com/huonw/primal"
documentation = "http://huonw.github.io/primal/primal_slowsieve/"
license = "MIT/Apache-2.0"
keywords = ["math", "mathematics", "primes", "number-theory"]

description = """
A simple sieve of Eratosthenes designed for testing faster sieves. You
probably want `primal-sieve`, or even just `primal` itself.
"""

[dependencies]
primal-bit = { path = "../primal-bit", version = "0.2" }
primal-estimate = { path = "../primal-estimate", version = "0.2" }
hamming = "0.1"

[features]
unstable = []
